### ISSUE TITLE
Change y-axis to possibly start at zero

### ISSUE THREAD

**Issue by lannonbr** [lannonbr/vscode-issue-tracker#10]
A few people have commented that the data can get a little misleading if the y-axis labels are not in the viewport of the screen. Even though it does have labels with relative min and max values, looking directly at the data itself can be misleading to some so enforcing the y-axis to start at 0 may fix that.

**Comment by clankill3r** [comment]
I came to open the same issue :)

![is-truncating-the-y-axis-misleading-no-yes-30156297](https://user-images.githubusercontent.com/738650/47707628-96b64700-dc2c-11e8-9660-bdf229a5b386.png)

<img width="752" alt="screen shot 2018-10-30 at 10 11 26" src="https://user-images.githubusercontent.com/738650/47707653-a9c91700-dc2c-11e8-8c5f-82ddfb003b83.png">

**Comment by lannonbr** [comment]
I think a solution that would work best would have a settings page that you could toggle on a y-axis that starts at 0 and that setting would be saved to localstorage. Then, both sides of people who may like this idea or who may not have the ability to choose the design they prefer.

**Comment by clankill3r** [comment]
I would make the default for that setting that it starts at zero so it is correct by default 😉

**Comment by lannonbr** [comment]
So I tried seeing what would happen if I set the y-axis to 0 and given the min and max for the graphs go between less than 100 issues on the daily chart and currently about 300-400 issues, in comparison to 4000 issues, the change is minimal and therefore would look like the chart isn't moving.

I'm sorry but I think keeping it as is now gives a higher insight when observing the charts given you can see relative changes over time better with a truncated y-axis. I'll be closing this issue as such.

**Comment by lannonbr** [comment]
Here's a screenshot of the two charts for reference when I did such:

![image](https://user-images.githubusercontent.com/3685876/47759914-55538500-dc88-11e8-8704-a569d77e1154.png)
