### ISSUE TITLE
Show Open Issues for the Last Year

### ISSUE THREAD

**Issue by ghost** [lannonbr/vscode-issue-tracker#15]
It would be nice to see a timeline of open issues for the last year.  This is similar to #13, but that issue asks for *all* history.  So all in all, I think it would be valuable to see:

- Last 3 Days
- Last Month
- Last Year
- All time

**Comment by lannonbr** [comment]
Yeah I think implementing some sort of filter on the graphs so you can customize the time duration you wish to see. With how the architecture currently works, I will only be able to show as far back as when I started collecting the data on a repo
