### ISSUE TITLE
Document setup

### ISSUE THREAD

**Issue by lannonbr** [lannonbr/vscode-issue-tracker#2]
Document the setup process for the vscode-issue-tracker.

The architecture is currently across multiple clouds (AWS, GCP, Azure (likely)), which has a bit of complexity, so making sure that everything is detailed.

- [ ] AWS Lambda for the function to hit the GitHub API and store data to Firebase Firestore database
- [ ] Firebase Firestore (GCP) to store data from GitHub API
- [ ] Frontend currently hosted on netlify (but can technically be on any hosting provider)

**Comment by saulshanabrook** [comment]
I would love to use this on the JupyterLab repo as well, so some steps on how to set this up for another repo would be great.

**Comment by andersy005** [comment]
Great tool @lannonbr. I am interested in how to set this up for another repo as well!

**Comment by B3nnyL** [comment]
I can help with Firestore and static site hosting.  

Btw, I'm curious why don't you use Firebase Function for data fetching?

**Comment by lannonbr** [comment]
@B3nnyL, I am thinking of trying to improve the infrastructure to be a bit more close together, but I do not believe Firebase's functions have scheduled triggers yet which is a requirement for this project.

**Comment by B3nnyL** [comment]
@lannonbr I see, I had the same issue and solved with task scheduling with GCP.  This link may help you. https://firebase.googleblog.com/2017/03/how-to-schedule-cron-jobs-with-cloud.html

**Comment by lannonbr** [comment]
@B3nnyL Although that is a way of doing such, it is just a little too complex for this. I want to make things simpler and reduce resources rather than increasing the amount if I condense to a smaller amount of cloud providers I use.

**Comment by lannonbr** [comment]
So I could document the instructions on how I set this project up, but with interest from the community as well as myself of using this for other projects, I want to try to make something that allows to easily replicate a project similar to this with a few things to setup and then be able to easily deploy it.

With such, see Issue #9 for more information, and I would love to hear everyone's comments & suggestions on the matter :smile:
