### ISSUE TITLE
Genralize infrastructure behind the issue tracker

### ISSUE THREAD

**Issue by lannonbr** [lannonbr/vscode-issue-tracker#9]
Many people have requested how this was made and as well, I myself want to make other websites that have a very similar infrastructure for GitHub-based statistic trackers.

Currently everything was manually setup while I believe a better situation is to have a more structured and laid out base. Tasks such as provisioning the various functions and databases to be a one command deploy after minimal config setup would be the ideal situation. A product that a developer can create graph visualizations and find insights into codebases.

I am wanting to dive into centralizing towards a solution that could be used either with cloud software or entirely on-prem. Here are some ideas for such I currently have (and if you can think of ways of doing these things that may be better or different than what I think, please add a comment below with such).

On-prem:
* Switch from firebase to some self-hosted database (Either NoSQL or Relational Databases could work for this)
* cronjobs / systemd timers to set up scheduled scripts?

Cloud-based:
* centralize to as few cloud providers as possible / work to allow transfer between clouds be as painless as possible
* setup orchestration workflow to spin up resources (AWS CloudFormation, Azure Resource Manager, Terraform, etc)
* Add monitoring for the infrastructure

**Comment by saulshanabrook** [comment]
Thanks for opening this discussion up. 

Another option would be to host many projects together, effectively turning this into SaaS. Then you could query any GitHub project or at least ones in which it's been enabled. 

This would require someone to step forward to pay for hosting and maintenance on this, but would make it much easier for other projects to use.

**Comment by lannonbr** [comment]
After looking some more, the library for easily writing GitHub apps, [Probot](https://github.com/probot/probot), actually has support to trigger events on a timer through a [scheduler extension](https://github.com/probot/scheduler).

This could be used to do the query to Github's API to grab whatever kind of data you want at a set interval as well as store a local set of data. Then it could use Github's API to create the new cached data file and commit it all through a Github App. Then the only setup that would need to be done would be setup a database to store the data, setup the Github App, and then setup some deployment for the static site and things could just work.

As well, another possibility is trying the newly announced Github Actions to on a schedule, trigger a workflow to do these various things of querying the Github API & updating the local files in the repo and making automated commits as well.

**Comment by lannonbr** [comment]
As well thinking further, we could remove the need for a DB given the data history could just be stored in files inside a repo and tracked through git. Since I am pulling data from Github's API and have an already local set of the history of data we already have seen, we could combine the two so the need for an external DB is no longer needed.

Finally, the more I think about this, having a SaaS for this project would be extremely powerful so everything could be contained in one place to manage the solution, but that said, I think a more unified solution that someone can get spun up in less than 30 minutes from a template is a higher priority. Once people can start using it for their projects in a semi-automated way, then possible brainstorming to see if making a SaaS for this GitHub data visualization project could come.

**Comment by fabioberger** [comment]
I'm interested in the template approach. How soon do you think I could give that a go?

**Comment by lannonbr** [comment]
Thinking further, I think building up a system with containers I think will be a good approach. Then as long as you have docker or a similar tool to spin up containers, you can manage it however you wish. If you want to setup cron jobs to run the containers on a schedule you will be able to. If you want to use a scheduler on AWS, Azure, etc, you will be able to. Given the data collection isn’t real-time, these will be short lived containers which will greatly reduce the costs compared to a continuously running service.

I think the architecture I want to now set up is a SaaS that allows people to login with GitHub and orchestrate the visualizations easily but if they want to run it on-prem they should be able to do so.

With a timeline on the progress with this, I would like to start writing some design docs shortly and have a majority for what I can be transparent. I hope to start working on some prototypes this week.

**Comment by ghost** [comment]
@lannonbr  It seems like the most user-friendly thing would be to have a text input somewhere on the page that allows users to enter the name of the repo for which they want to view stats.  A change handler on that textbox would send a request to your Lambda Function that polls the latest history for the last 3 days, month, year, etc.  As long as you have some kind of loading circle or progress bar, I think users will be willing to wait, and all of this can be done with simple JavaScript, no server-side framework needed.

I also feel like you could simplify things on the backend (please educate me if this is a terrible idea).  Why have one Function that goes from GraphQL to Firestore, and another that goes from Firestore to this repo?  Why not just have one Function that queries GraphQL, returning the results as JSON, and then have your front end update the C3 charts from that response?  If that single Function expects the name of a repo, then boom, you support stats for any GitHub repo!

**Comment by lannonbr** [comment]
@DanAtkinson at least as far as I know, GitHub's api doesn't store the history of these realtime queries for things like issues, PRs, etc, so I have to generate a database to store them. If you can find otherwise that they do, do tell because then in that instance I totally would agree that a single static frontend that you can enter a repo on GitHub and get stats about it would be the best solution, but at this moment, I have to store the data myself, and given the scale of the repos on GitHub, I am not in the position to pay to collect the data / store it for literally millions of repos.

If you can figure out if GitHub stores this data that is accessible through either their V3 REST api or their V4 GraphQL api, I would be fully willing to use those endpoints instead of making my own.

**Comment by DanAtkinson** [comment]
@lannonbr Yeah, that's not me. You'll want @DanVicarel. 🤣

**Comment by ghost** [comment]
Ah, well yes that would explain why you didn't take that approach.  I shall begin the googles to see if this is possible...

**Comment by ghost** [comment]
So you already have the means to get the number of closed Issues with:

```gql
query {
  repository(owner:"repoOwner", name:"repoName") {
    issues(states:CLOSED){
      totalCount
    }
  }
}
```

With that count, you know how many times you need to query 100 closed Issues in a repo until you have them all (the max value for `first`/`last` is 100).  If you only request the `createdAt`  field for each Issue, then those requests are really quick, and you can use the `after` field to correctly paginate.  Those GraphQL queries would look like:

```gql
query {
  repository(owner:"repoOwner", name:"repoName") {
    issues(first:100, after:"cursor...", states:CLOSED, orderBy:{direction:ASC, field:CREATED_AT}){
      pageInfo{
        endCursor
        startCursor
      }
      nodes{
        createdAt
      }
    }
  }
}
```

If you shove all of those `createdAt` times in an array, then it'll be trivial to count how many Issues were in the last 3 days, last month, etc.  Most repos have numbers of issues [in the thousands or less](https://www.xplenty.com/blog/github-issue-analysis-2013/), so I don't think you'll need to worry about hitting time or memory limitations in Lambda.

You can then call this function every time the user refreshes the page or changes the owner/name text inputs.

**Comment by ghost** [comment]
For that matter, this stuff doesn't even really need to run in Lambda, it could just run right in the browser, which would have the added benefit of letting you update a progress bar.

**Comment by lannonbr** [comment]
I'll take a look into your solution, but that said, GitHub does have a rate limit for their API so I will have to see if that will be taxing on the limit

**Comment by lannonbr** [comment]
I also just remembered, you can now delete issues off of github so the numbers could be skewed because of such, so using your solution to try getting historical records may not be the best given it may not be as accurate.

**Comment by ghost** [comment]
Hm, I would think that if somebody deletes an Issue, they wouldn't want it showing up in history charts either...

**Comment by lannonbr** [comment]
True, but I am not showing the actual issues but rather the total counts at the time so I don't think it is unjust to use the data at that time even if it changes.

**Comment by ghost** [comment]
It's a judgement call, but I'd say if you have logic that shows the number of Issues for any repo over any time scale without having to store all of that history yourself, and doesn't include Issues that the owners of the repos deleted... that'll be like exactly what most users are hoping for.  To say it another way, if I created 10 Issues last month, then delete one of those Issues, and now my history shows only 9 Issues last month...I would not be bothered; in fact that's exactly what I would expect to see.  I wanted that Issue *gone* from history.

**Comment by ghost** [comment]
There's some good discussion over here about [why GitHub users want to delete Issues](https://github.com/isaacs/github/issues/253).

**Comment by lannonbr** [comment]
Let me at least try your solution of using the API. If I were to do such, I would have users login with GitHub and use their tokens to hit the API. I will do a test run this evening and try to get some numbers for how much of the rate limit these queries take.

**Comment by lannonbr** [comment]
@DanVicarel So your implementation works up to a point. Yes it does look like I can parse the entirety of a repo's project by going through issues in bunches of 100 and move backwards until I collect all of the data that I wish, and for small projects, the rate limit isn't too taxing, but as soon as you look at the larger repos, it pushes the boundaries.

With the V4 GraphQL api, instead of 5000 requests per hour, it is 5000 "points" per hour which is being calculated differently compared to the REST API given you are only grabbing the information you need with GraphQL. With respect to the usage for this project, If I request 100 issues and 100 pull requests in a single request, that equates to 1 point per hour, which is alright with small projects.

That said, what if I go request historical data with your method for something like VS Code. It has over 60k issues, 4k pull requests and 64k stars. If I want to collect all of that data, at the 100 per request, it would take over 600 requests with the single query which is 12% of the hourly quota.

As well, the historical data for the most part will not change over time so if I can do the heavier calculations on a server rather than someone's client, it is going to be more efficient when a user requests the data rather than hitting the API every time and doing the calculations, I could have a personal API that has the exact data I need to then render graphs depending on what the user requests.

That said, with the idea of having a simple interface that can query this data with my version that I am trying to define just is not scalable for me. There's over 100 billion repos on GitHub so I cannot think of collecting data for every single one. We are talking about google/amazon scale of data collection and for a single developer who is doing this for fun, I don't have endless funds to manage this. With such, my implementation of having a hosted service that people could pay for and have me manage the collection and have it be able to be installed on-prem so if someone wishes to use their own resources for it they can.

With all of this, provisioning collections on a per-repo basis based upon how I currently do it and cache it to a database is more resources on my end, but I personally think it may be the best solution initially. I'd wish there was a solution that could take the best of each solution, but I don't believe with GitHub's rate limits that it is doable right now. It isn't the best with the issue that you brought up on deleting issues, but it's just going to be have to be how it is.
